### ISSUE TITLE
Redo UI

### ISSUE THREAD

**Issue by jaesivsm** [jaesivsm/JARR#90]
Redo Existing : 
### login page : 
- [x] login / password
  - [x] persist creds
- [x] login with google
- [x] logout 
- [x] retry http request with refreshed token on expiration
### menu
- [x] listing categories
  - [x] folding / unfolding 
  - [x] folding all / unfolding all 
- [x] listing feeds
  - [x] with icons 
  - [x] with unread counts
  - [x] sorted by unread counts
- [x] filtering 
  - [x] filtering by feed
  - [x] filtering by category
  - [x] filtering by read status
  - [x] filtering by liked status
- [x] search through feeds
- [ ] search through clusters 
- [x] sorting feeds by unread count
 
### content edtition 
- [x] add category  
- [x] allow feed creation (#72) 
  - [x] list proposed feed urls from feed constructor
  - [x] display warnings for existing feed
  - [x] display for data validation (missing link)
- [x] allow feed edition (#47)
  - [x] edit / add feed filters
  - [x] style 
  - [x] delete from card (#70) 
- [x] allow category edition 
  - [x] fold advanced settings by default 
  - [x] delete from card
- [x] mark all as read 
  - [x] update unread counters
- [x] mark all non cluster as read 
- [x] edit user / password 
- [ ] export / import OPML

### cluster reading
- [x] clusters listing 
  - listing usability: 
    - [ ] #73 auto refresh 
    - [ ] #46 infinite scroll / pagination on clusters 
  - control options : 
    - [x] read / unread 
       - [x] no wait time when marking as read (#76)
    - [x] liked / unliked
    - [x] read on open 
    - [x] unread on close
  - [x] properly formated content 
- [x] show tab if several article 
- [x] display tabs in panel if large display

## NTH : 
- [ ] keyboard shorcut (#36) (#64)

## docker 
- [x] building docker image with client
